# Generated by Django 5.0.7 on 2024-07-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0002_alter_artista_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='tipo_chave_pix',
            field=models.CharField(choices=[('cel', 'Celular'), ('cnpj', 'CNPJ'), ('email', 'E-mail'), ('cpf', 'CPF')], default='cel', max_length=10),
        ),
    ]
