# Generated by Django 5.0.7 on 2024-07-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0003_alter_artista_tipo_chave_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
